### PR TITLE
Fixes #5 #8 #9 Integrate a prototype bootstrap, update header footer with smoothscrolling sidebar

### LINKED ISSUE #5: Integrate a prototype bootstrap layout for the theme
### Description
Since it was decided that we will be inhering the basic theme and extend that, we can now update with structuring the layout using bootstrap components. 

Bootstrap library will be used because it is highly responsive and also as the template for FOSSASIA's main website and other children web site's are created using Bootstrap.

Parent issue: https://github.com/fossasia/sphinx_fossasia_theme/issues/3

### PR DESCRIPTION
**Pull request by imujjwal96**
### Description
As discussed, the basic theme has been extended. Since almost all the html tags will change in the `layout.html` file, I chose not to extend the `basic/layout.html` file. Also , it becomes difficult in including multiple CSS file, none of which i thought were useful.

### Issue
Fixes issue #5 

### Screenshot
image
It is just a prototype with added bootstrap components. It is also responsive (as intended)
image

### CODE REVIEW

**Comment by imujjwal96** [comment]
@mariobehling  @pri22296  @sch00lb0y  Please review.

**Comment by poonai** [comment]
could you show us the rendered HTML? host it using surge or any other tool.

**Comment by imujjwal96** [comment]
Here: http://163.172.11.243:8080/xyz/

**Comment by poonai** [comment]
whatsapp image 2017-07-07 at 6 17 33 pm
When I open in mobile the menu button not rendering but when I changing resolution on a computer it's coming. is there any way to avoid this?

**Comment by imujjwal96** [comment]
Oh yes there is. Will have to add a meta tag for the content will.
Thanks for noticing.

**Comment by imujjwal96** [comment]
@sch00lb0y Please check again!

**Comment by pri22296** [comment]
@imujjwal96 Checked. That issue has been fixed.

Please see the following issues

- In the menu bar, why is `docs` written as a subscript of `FOSSASIA`?
- Upon opening and then closing the menu, the menu button stays selected

**Comment by imujjwal96** [comment]
1 is just a design choice. We'll most probably place FOSSASIA's logo there.

**Comment by imujjwal96** [comment]
2 -> ie how it works with Bootstrap. I've looked at multiple sites created using it having the same design

**Review by pri22296 — APPROVED** [review]
Looks good

**Review by poonai — APPROVED** [review]

**Comment by imujjwal96** [comment]
@mariobehling  Please review.

**Comment by imujjwal96** [comment]
Here's the updated theme:
image

**Comment by imujjwal96** [comment]
Here is the updated theme.
image

**Comment by imujjwal96** [comment]
@pri22296  @sch00lb0y  Please review.

**Comment by pri22296** [comment]
Can you share a deployment?

**Comment by imujjwal96** [comment]
http://163.172.11.243:8080/sam/

**Comment by pri22296** [comment]
Clicking on a link in the sidebar leads to the title being hidden under the menu bar
screenshot 178

**Comment by imujjwal96** [comment]
@pri22296 updated it

**Comment by pri22296** [comment]
In the sidebar, there is no way to differentiate which link is a new link and which is a continuation of the previous link. Should something be done about that?

**Comment by imujjwal96** [comment]
@pri22296 updated it.

**Review by pri22296 — APPROVED** [review]
Nice job

**Pull request merged**
